---
- hosts: allnodes
  name: Gather all facts
  vars_files:
  - "variables.yml"
  tasks: [ ]

- hosts: ui
  user: "{{ ssh_login }}"
  become: true
  become_method: sudo
  vars_files:
  - "variables.yml"
  gather_facts: False

  tasks:
  - name: VNC Server Setup Script
    copy: src="{{ topfolder }}/scripts/{{ item }}" dest="/home/{{ ssh_login }}/{{ item }}" owner="{{ ssh_login }}" mode=0550
    with_items:
    - setup-vncserver.sh

  - name: Ensure VNC Server is running
    shell: ./setup-vncserver.sh l.login "{{ ui_password_vnc }}"

