---
- hosts: allnodes
  name: Gather all facts
  vars_files:
  - "variables.yml"
  tasks: [ ]

#
# Create 'admin' user on tools node
- hosts: tools
  user: "{{ ssh_login }}"
  become: true
  become_method: sudo
  vars_files:
  - "variables.yml"
  gather_facts: False

  tasks:
  - name: Create admin user (no password)
    user:
      name: admin
      comment: "Ambari Admin User"
      shell: /bin/bash

- hosts: tools
  user: "{{ ssh_login }}"
  become: true
  become_method: sudo
  vars_files:
  - "variables.yml"
  gather_facts: False

  tasks:
  - name: Copying helper scripts for admin
    copy: src="{{ topfolder }}/scripts/{{ item }}" dest="/home/admin/{{ item }}" owner=admin mode=0550
    with_items:
    - mapper.R
    - reducer.R
    - cars.csv

