---
- hosts: allnodes
  name: Gather all facts
  vars_files:
  - "variables.yml"
  tasks: [ ]

- hosts: master:data:tools
  user: "{{ ssh_login }}"
  become: true
  become_method: sudo
  vars_files:
  - "variables.yml"
  gather_facts: False

  tasks:
  - name: Configure Ambari server name on each agent
    ini_file:
     dest: /etc/ambari-agent/conf/ambari-agent.ini
     section: server
     option: hostname
     value: "edge.{{ domainname }}"

  - name: Restart Ambari agent
    service: name=ambari-agent state=restarted

  - debug: msg="Ambari Agents reconfigured"

