region: ap-southeast-2
pemkey: "{{ lookup('env', 'PEMKEY') }}"
access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
clustername: "{{ lookup('env', 'HDPCLUSTERNAME') }}"
edgenode_instancetype: "{{ lookup('env', 'EDGENODETYPE') }}"
hdpmaster_instancetype: "{{ lookup('env', 'MASTERNODETYPE') }}"
hdpslave_instancetype: "{{ lookup('env', 'SLAVENODETYPE') }}"
number_of_nodes: "{{ lookup('env', 'NUMNODES') }}"
root_ebs_size: "{{ lookup('env', 'EBSVOLSIZE') }}"
vpc_cidr_block: 10.0.0.0/16
vpc_subnets:
 - cidr: 10.0.1.0/24
   az: ap-southeast-2a
vpc_internet_gateway: "yes"
vpc_route_tables:
 - subnets:
    - 10.0.1.0/24
   routes:
    - dest: 0.0.0.0/0
      gw: igw
imageid: ami-b72fb78d
oracle_jdk_download: "http://download.oracle.com/otn-pub/java/jdk/7u51-b13/jdk-7u51-linux-x64.rpm"
oracle_jdk_version: jdk1.7.0_51
hdp_ambari_repo: "http://public-repo-1.hortonworks.com/ambari/centos6/2.x/updates/2.0.0/ambari.repo"
java_alternatives: "{{ lookup('file', '../scripts/java_alternatives.sh') }}"

